# Generated by Django 4.0.3 on 2022-03-10 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Municipios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('depatamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Prestadores.departamentos')),
            ],
        ),
        migrations.CreateModel(
            name='SedesPrestador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_prestador', models.CharField(blank=True, max_length=60, null=True)),
                ('codigo_habilitacion', models.CharField(max_length=10, unique=True)),
                ('nit', models.CharField(blank=True, max_length=10, null=True)),
                ('dv', models.IntegerField(default=0)),
                ('clase_persona', models.CharField(blank=True, max_length=60, null=True)),
                ('naturaleza', models.CharField(blank=True, max_length=60, null=True)),
                ('clase_prestador', models.CharField(blank=True, max_length=60, null=True)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Prestadores.municipios')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleSede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_sede', models.CharField(blank=True, max_length=2, null=True)),
                ('nombre', models.TextField(blank=True, null=True)),
                ('gerente', models.CharField(blank=True, max_length=60, null=True)),
                ('direccion', models.CharField(blank=True, max_length=60, null=True)),
                ('telefono', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.CharField(blank=True, max_length=130, null=True)),
                ('fecha_apertura', models.CharField(blank=True, max_length=60, null=True)),
                ('horario_lunes', models.CharField(blank=True, max_length=60, null=True)),
                ('horario_martes', models.CharField(blank=True, max_length=60, null=True)),
                ('horario_miercoles', models.CharField(blank=True, max_length=60, null=True)),
                ('horario_jueves', models.CharField(blank=True, max_length=60, null=True)),
                ('horario_viernes', models.CharField(blank=True, max_length=60, null=True)),
                ('horario_sabado', models.CharField(blank=True, max_length=60, null=True)),
                ('horario_domingo', models.CharField(blank=True, max_length=60, null=True)),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Prestadores.sedesprestador')),
            ],
        ),
    ]
