# Generated by Django 4.0.3 on 2022-03-14 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prestadores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamentos',
            options={'verbose_name_plural': '1. Crear los Departamentos'},
        ),
        migrations.AlterModelOptions(
            name='detallesede',
            options={'verbose_name_plural': '2.1. Crear Las Sedes'},
        ),
        migrations.AlterModelOptions(
            name='municipios',
            options={'verbose_name_plural': '1.1. Crear los Municipios'},
        ),
        migrations.AlterModelOptions(
            name='sedesprestador',
            options={'verbose_name_plural': '2. Crear Prestadores'},
        ),
        migrations.RemoveField(
            model_name='sedesprestador',
            name='codigo_habilitacion',
        ),
        migrations.AddField(
            model_name='detallesede',
            name='codigo_habilitacion',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
