# Generated by Django 4.0.3 on 2022-04-03 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prestadores', '0002_alter_departamentos_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallesede',
            name='es_usada',
            field=models.BooleanField(default=False),
        ),
    ]
