# Generated by Django 4.0.3 on 2022-04-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prestadores', '0004_alter_sedesprestador_dv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallesede',
            name='codigo_habilitacion',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
