# Generated by Django 4.0.3 on 2022-04-07 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prestadores', '0007_alter_sedesprestador_clase_persona_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sedesprestador',
            name='nombre_prestador',
            field=models.TextField(blank=True, null=True),
        ),
    ]
