# Generated by Django 4.0.3 on 2022-04-07 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prestadores', '0008_alter_sedesprestador_nombre_prestador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sedesprestador',
            name='nit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
