# Generated by Django 4.0.3 on 2022-04-07 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prestadores', '0009_alter_sedesprestador_nit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallesede',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
